name: Continuous Integration

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:

  continuous-integration:
    name: Continuous Integration

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
        dependencies:
          - 'highest'
        include:
          - php-version: '7.2'
            dependencies: 'lowest'
          - php-version: '8.1'
            dependencies: 'lowest'
          - php-version: '8.1'

    steps:
      # Cancel previous runs of the same branch
      - name: cancel
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          tools: composer:v2

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: '${{ matrix.dependencies }}'

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      - name: Validate composer
        run: composer validate --strict --no-check-lock

      - name: phpstan-cache
        uses: actions/cache@v2
        with:
          key: phpstan-${{ matrix.php-version }}-${{ matrix.dependencies }}-${{ github.ref }}-${{ github.sha }}
          path: .phpstan-cache
          restore-keys: |
            phpstan-${{ matrix.php-version }}-${{ matrix.dependencies }}-${{ github.ref }}-
            phpstan-${{ matrix.php-version }}-${{ matrix.dependencies }}-
            phpstan-${{ matrix.php-version }}-
            phpstan-

      - name: Run phpstan
        run: composer phpstan

      - name: Run php_codesniffer
        run: composer cs-check
        if: ${{ matrix.php-version == '7.2' }} # Do not suggest using features after 7.2
