name: Continuous Integration

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:

  continuous-integration:
    name: Continuous Integration

    runs-on: ubuntu-latest

    strategy:
      matrix:
        install-args: ['', '--prefer-lowest']
        php-version: ['7.2', '7.3', '7.4', '8.0']
      fail-fast: false

    steps:
      # Cancel previous runs of the same branch
      - name: cancel
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: composer-cache-dir
        id: composercache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.json') }}-${{ matrix.install-args }}
          restore-keys: |
            composer-${{ hashFiles('**/composer.json') }}-${{ matrix.install-args }}
            composer-${{ hashFiles('**/composer.json') }}-
            composer-

      - name: Install dependencies
        run: |
            composer update ${{ matrix.install-args }} --no-interaction --no-progress --prefer-dist
        if: ${{ matrix.php-version != '8.0' }}

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit

      - name: Validate composer
        run: composer validate --strict --no-check-lock

      - name: phpstan-cache
        uses: actions/cache@v2
        with:
          key: phpstan-${{ matrix.php-version }}-${{ matrix.install-args }}-${{ github.ref }}-${{ github.sha }}
          path: .phpstan-cache
          restore-keys: |
            phpstan-${{ matrix.php-version }}-${{ matrix.install-args }}-${{ github.ref }}-
            phpstan-${{ matrix.php-version }}-${{ matrix.install-args }}-
            phpstan-${{ matrix.php-version }}-
            phpstan-

      - name: Run phpstan
        run: composer phpstan

      - name: Run php_codesniffer
        run: composer cs-check
        if: ${{ matrix.php-version == '7.2' }} # Do not suggest using features after 7.2
